### N4KXLQI4AHXW2N75

### Serch
GET http://localhost:3030/dashboard/search/ba

### Quote
GET http://localhost:3030/dashboard/quote/BA

### GainLoss
GET http://localhost:3030/dashboard/quote/BA/gainloss?date_consulting=10-27-2023

### Quote History
GET http://localhost:3030/dashboard/history/BA?start_date=10-27-2023&end_date=10-22-2023

### Quote History Invalid Start Date
GET http://localhost:3030/dashboard/history/BA?start_date=27-10-2023&end_date=10-27-2023

###
GET https://www.alphavantage.co/query?function=SYMBOL_SEARCH&keywords=IBM&apikey=N4KXLQI4AHXW2N75